{
 "title": "EcoMarket Observability",
 "tags": [
  "ecomarket",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Estado ms-carrito",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ms-carrito\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"ms-carrito\"}[1m]))",
     "legendFormat": "requests/s"
    }
   ]
  },
  {
   "title": "Latencia promedio HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"ms-carrito\"}[1m]) / rate(http_server_requests_seconds_count{job=\"ms-carrito\"}[1m])",
     "legendFormat": "latencia promedio"
    }
   ]
  },
  {
   "title": "Logs ms-carrito",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"ms-carrito\"}"
    }
   ]
  }
 ]
}